import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "aos/dist/aos.css"; // ✅ ✅ ✅ AOS CSS MUST be imported here

import Navbar from "./navbar/page";
import Footer from "./footer/page";
import AOSProvider from "./components/aosprovider"; // ✅ Correct

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Huboweb",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-gradient-to-r from-[#070121] to-[#170080]">
        <AOSProvider /> {/* ✅ Initializes AOS on client side */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
